### ISSUE TITLE
Shell Completions

### ISSUE THREAD

**Issue by newtonj** [jasedit/scriptorium#20]
In the same vein as git's subcommands such as `git add`, etc. having the ability to tab-complete things like `scriptorium bu` to `scriptorium build` would be a quality of life improvement for command-line users.

**Comment by jasedit** [comment]
A branch has been added that adds the capability, but still requires the user to run:

```
eval "$(register-python-argcomplete scriptorium)"
```

at the command line once to register the autocompletion with bash.
