### ISSUE TITLE
Error during setup

### ISSUE THREAD

**Issue by rjgriffin42** [jasedit/scriptorium#78]
When trying to setup scriptorium on a new Ubuntu 16.04 computer, when the command `sudo python -c "import pymmd; pymmd.build_mmd()"` is run, the following is reported

```
Entering 'submodules/greg'
Already up-to-date.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/robert/.local/lib/python2.7/site-packages/pymmd/download.py", line 65, in build_mmd
    subprocess.call(cmake_cmd)
  File "/usr/lib/python2.7/subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

This prevent the rest of the install from working.

**Comment by jasedit** [comment]
That implies cmake hasn't been installed - can you verify that it is installed?

**Comment by rjgriffin42** [comment]
It was not, and that solved that issue.

**Comment by rjgriffin42** [comment]
correction: it gets most of the way through compiling, then segfaults out.

**Comment by rjgriffin42** [comment]
After executing the python commands in the shell, it works ( I think). Not sure why that fixes it, but it did.

**Comment by jasedit** [comment]
How were you running the command previously, out of curiosity?

**Comment by rjgriffin42** [comment]
using the one indicated in the README. Calling the commands directly in an instance of python still throws a segfault error when I exit python, but it finished something or another that makes the `scriptorium` command recognizable

**Comment by jasedit** [comment]
So executing commands in an instance of python caused the interpreter to report segfaults on exit, but running directly from the terminal in batch mode fixed it?
