### ISSUE TITLE
Breaking out abstracts into separate files.

### ISSUE THREAD

**Issue by newtonj** [jasedit/scriptorium#8]
Current template implementations such as [vtthesis](https://github.com/jasedit/vtthesis) have sections such as the abstract and acknowledgements embedded in the metadata.tex file. It'd be snazzy to have the ability to define those as external multimarkdown files to ease creation and maintenance.

**Comment by jasedit** [comment]
Feature has been added in 7e7fc7dc1706d9e61e354808ecf6acfc3dfd3370

**Comment by jasedit** [comment]
Fixed.
