### ISSUE TITLE
doctor command should respect the LATEX_CMD configuration value

### ISSUE THREAD

**Issue by jasedit** [jasedit/scriptorium#81]
When executing `scriptorium doctor`, the LaTeX package test should read and use the `LATEX_CMD` configuration value for consistency

**Comment by mwspicer** [comment]
If it helps, this currently works for me. I didn't have xelatex installed, and, with `LATEX_CMD: xelatex` in the config file, `scriptorium doctor` complained about latex. Setting `LATEX_CMD: pdflatex` (which is installed) caused scriptorium doctor to return nothing.

**Comment by jasedit** [comment]
If you install xelatex and set that as the version, does it no longer complain?

**Comment by mwspicer** [comment]
Yes, installing xelatex and setting `LATEX_CMD: xelatex` also causes `scriptorium doctor` to return nothing.

**Comment by jasedit** [comment]
This that confirms this has been fixed. Thanks for the debug/test help!

**Comment by mwspicer** [comment]
Glad to help!
