### ISSUE TITLE
Size of image on new install being completely disobeyed

### ISSUE THREAD

**Issue by rjgriffin42** [jasedit/scriptorium#82]
I know this was an issue that you previously took care of, but it unfortunately did not get documented. When I include an image, it appears absolutely enormous in the document.

**Comment by jasedit** [comment]
How are you inserting the image?

**Comment by rjgriffin42** [comment]
Im using the includegraphics command, trying both png and eps files

**Comment by jasedit** [comment]
That's a LaTeX issue, not a scriptorium issue. Your best bet would be to look up documentation on how includegraphics handles automatic image sizes (IME, not terribly well) and how to set the size properly.
