### ISSUE TITLE
Error on building document

### ISSUE THREAD

**Issue by DTChuck** [jasedit/scriptorium#88]
Attempted to build a new document after completing the configuration in paper.mmd, but python errors occurred. Paper files are attached below.

[tree_classification.zip](https://github.com/jasedit/scriptorium/files/1177787/tree_classification.zip)

 $ scriptorium build
Traceback (most recent call last):
  File "/usr/local/bin/scriptorium", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/scriptorium/__main__.py", line 181, in main
    args.func(args)
  File "/usr/local/lib/python3.4/dist-packages/scriptorium/__main__.py", line 17, in build_cmd
    keep_comments=args.keep_comments)
  File "/usr/local/lib/python3.4/dist-packages/scriptorium/papers.py", line 116, in to_pdf
    fname = paper_root(paper_dir)
  File "/usr/local/lib/python3.4/dist-packages/scriptorium/papers.py", line 33, in paper_root
    if get_template(fname):
  File "/usr/local/lib/python3.4/dist-packages/scriptorium/papers.py", line 54, in get_template
    idx = mmf.find(_BLANK_LINK)
TypeError: must be read-only pinned buffer, not bytearray

**Comment by DTChuck** [comment]
Was using the ieeetran template. Gonna try re-downloading the templates to see if that helps.

**Comment by jasedit** [comment]
I get a different build error, because `my acknowledgements` is defined as an empty string.

Putting in a dummy acknowledgements file, I don't get this error. It looks like this may be due to a different version of python? Are you easily able to switch to python 3.5 or possibly python 2.7?

**Comment by DTChuck** [comment]
I can check 2.7 tomorrow and see if I get the same error.

Ryan Brown
Ph.D. Candidate
Mechatronics Lab
Virginia Tech

On Jul 26, 2017, at 4:13 PM, Jason <notifications@github.com<mailto:notifications@github.com>> wrote:


I get a different build error, because my acknowledgements is defined as an empty string.

Putting in a dummy acknowledgements file, I don't get this error. It looks like this may be due to a different version of python? Are you easily able to switch to python 3.5 or possibly python 2.7?

**Comment by jasedit** [comment]
Version 2.7.2 contains the fix to this issue, and has been uploaded to pip. Executing `pip install -U scriptorium` should update to the latest version.
